### ISSUE TITLE
traffic lights, stop signs, and visuals (CSS)

### ISSUE THREAD

**Issue by SebastianKropp** [Stopless-Intersection-Mgmt-Program/simp#5]
To meet our sprint 1 goals we need a simple visual interface for traffic lights & stop signs. 

Create multiple divs positioned where the road meets the intersection. This div should either represent a stop sign, or a traffic light with two states depending on whether the lane should stop for traffic, or proceed through the intersection. these two states should be visually distinguished as red, and green respectively.

**Comment by jwxu1688** [comment]
Code reviewed and checked. Changes are in the current development merge.
