### ISSUE TITLE
Car Spawner

### ISSUE THREAD

**Issue by SebastianKropp** [Stopless-Intersection-Mgmt-Program/simp#8]
Our current plans for simp require that we generate cars through our frontend. To accommodate this we need to create a carComponent which stores random variables: car dimensions, coordinates (x,y within world),  speed, color, startPoint, endPoint.

We also need a function to check if a startPoint is currently occupied by another car before spawning a carComponent. To quickly retrieve startPoints and endPoints use the degreesToCoords( radius, degrees, error (roadwidth/2) ) function to retrieve the starting location of each road in an intersection type. 

Effectively places cars at available starting points for scenarios, and renders cars onto the interface.

Passes data to car managing function

**Comment by RezaP117** [comment]
Reviewed and checked, Car Spawner works as intended and is in current development merge.
